CREATE DATABASE SystemUMG;
USE PROGRA;
-- CREAR TABLA
-- CURSOS
CREATE TABLE CURSOS(
CÓDIGO INT,
CURSO VARCHAR(45),
CICLO INT,
REQUISITOS INT
);

SELECT*FROM CURSOS;
-- registros
INSERT INTO CURSOS
(CÓDIGO, CURSO, CICLO, REQUISITOS) 
VALUES('018','CÁLCULO II','04','013');

-- INSCRIPCIÓN
CREATE TABLE INSCRIPCIÓN(
CARNÉ INT,
NOMBRE VARCHAR(45),
APELLIDO  VARCHAR(45),
CARRERA  VARCHAR(45),
CICLO INT
);

SELECT*FROM INSCRIPCIÓN;
-- registros
INSERT INTO INSCRIPCIÓN
(CARNÉ, NOMBRE, APELLIDO, CARRERA, CICLO) 
VALUES('15474','SOMEBODY','ELSE','INGENIERÍA', '022022');

-- ASIGNACIÓN
CREATE TABLE ASIGNACIÓN(
CARNÉ INT,
NOMBRE VARCHAR(45),
APELLIDO  VARCHAR(45),
ASIGNACIÓN VARCHAR(45),
CARRERA  VARCHAR(45),
CICLO INT
);

SELECT*FROM ASIGNACIÓN;
-- registros
INSERT INTO ASIGNACIÓN
(CARNÉ, NOMBRE, APELLIDO, ASIGNACIÓN, CARRERA, CICLO) 
VALUES('15474','SOMEBODY','ELSE','001501','INGENIERÍA', '022022');